config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, controllers: { registrations: "user_registrations" }
  resources :products do 
    resources :comments
  end
  resources :users

  get 'static_pages/about' , :as => 'about_page'

  get 'static_pages/contact' , :as => 'contact_page'

  get '/products', to: 'products#index' , :as => 'products_page'

  get '/orders', to: 'orders#index', :as => 'orders_page'

  get 'static_pages/index'

  root 'static_pages#landing_page'

  post 'static_pages/thank_you'

  post 'payments/create'

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders, only: [:index, :show, :create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	  <title>Fancy Cakes</title>
	  <!-- bootstrap link -->
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	  <!-- custom css file link -->
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- javascript links go here -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <%# javascript_include_tag "application.js", "data-turbolinks-track" => true %>
    <!-- fonts go here -->
    <link href="https://fonts.googleapis.com/css?family=Cutive|Roboto|Clicker+Script" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>
  <body id="bootstrap-overrides">
	  <nav class="navbar navbar-default navbar-static-top">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a><%= link_to "Fancy Cakes", root_url %></a>
		    </div><!-- /.navbar-header -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav navbar-left">
		        <li><%= link_to 'Products', products_page_path %></li>
		        <li><%= link_to 'About', about_page_path %></li>
		        <li><%= link_to 'Contact', contact_page_path %></li>
		        <li><%= link_to 'Orders', orders_page_path %></li>
		      </ul>
		      <ul class="nav pull-right">
		      	<li>
		      	<% if user_signed_in? %>
		      		<%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "logout-button") %>
		      	<% else %>
		      		<%= link_to('Login', new_user_session_path, class: "login-button") %>
		      	<% end %>
		      	</li>
		      </ul>
		      <!-- begin search form -->
		    	<%= form_tag("/products", method: "get", class: "navbar-form navbar-right") do %>
  					<%= label_tag(:q, "Search for:", class: "search-for") %>
  					<%= text_field_tag(:q) %>
  					<%= submit_tag("Search", class: "search-button") %>
					<% end %>
		    <!-- end search form -->
		    </div><!-- /.collapse  /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>

		<% if notice %>
			<p class="alert alert-info alert-dismissible" role="alert" data-dismiss="alert">
				<%= notice %>
				<span class="closebtn">&times;</span>
			</p>
		<% end %>

		<% if alert %>
    	<p class="alert alert-info alert-dismissible" role="alert" data-dismiss="alert">
    		<%= alert %>
    		<span class="closebtn">&times;</span>
    	</p>
    <% end %>

  	<%= yield %>

	<footer>
		&copy; 2017 Callan Cook
	</footer>
  </body>
</html>